id: IB168FDBF
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W1KG12675
  ocr_info:
    timestamp: 02/22/24T17:03:52
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-22 11:33:52.998274+00:00
last_modified: 2024-02-22 11:33:52.998275+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12675
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12675
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཟུངས་མདོ་བརྒྱ་དང་དྲུག་ཅུ་རྩ་བདུན།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9049699761502331
  ocr_word_median_confidence_index: 0.97
bases:
  I1KG12703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12703
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12703.txt
    statistics:
      ocr_word_median_confidence_index: 0.97
      ocr_word_mean_confidence_index: 0.904270306104802
  I1KG12706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12706
      total_pages: 408
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12706.txt
    statistics:
      ocr_word_median_confidence_index: 0.97
      ocr_word_mean_confidence_index: 0.9056877657592657
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
